name: Super Linter

on:
  workflow_dispatch

jobs:
  super-linter:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Lint code base
        uses: super-linter/super-linter@v5.3.1
