name: Force Elementaire Opiniatre - Github Actions CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install --legacy-peer-deps
      - name: Run tests
        run: npm run test

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "force-elementaire-opiniatre"
          heroku_email: "kristono.sugiarto@gmail.com"